#!/sbin/busybox sh
(
	# order of modules load is important

#	if [ "$usbserial_module" == "on" ]; then
#		insmod /lib/modules/usbserial.ko;
#		insmod /lib/modules/ftdi_sio.ko;
#		insmod /lib/modules/pl2303.ko;
#	else
#		rmmod pl2303.ko;
#		rmmod ftdi_sio.ko;
#		rmmod usbserial.ko;
#	fi;
#	if [ "$usbnet_module" == "on" ]; then
#		insmod /lib/modules/usbnet.ko;
#		insmod /lib/modules/asix.ko;
#	else
#		rmmod asix.ko;
#		rmmod usbnet.ko;
#	fi;
	if [ "$exfat_module" == "on" ]; then
		insmod /lib/modules/exfat_fs.ko;
		insmod /lib/modules/exfat_core.ko;
		insmod /lib/modules/exfat_fs.ko;
	else
		rmmod exfat_fs.ko;
		rmmod exfat_core.ko;
	fi;
#	if [ "$eds_module" == "on" ]; then
#		insmod /lib/modules/eds.ko;
#	else
#		rmmod eds.ko;
#	fi;
#	if [ "$xpad_module" == "on" ]; then
#		insmod /lib/modules/ff-memless.ko;
#		insmod /lib/modules/xpad.ko;
#	else
#		rmmod xpad.ko;
#		rmmod ff-memless.ko;
#	fi;
	lsmod > /data/.nx_modules 2>&1;
	LMOD=`cat /data/.nx_modules`;
	echo "Loaded Modules:";
	echo " ";
	echo "$LMOD";
	rm -f /data/.nx_modules > /dev/null 2>&1;

)&
