#!/sbin/busybox sh

PROFILE=`cat /data/.siyah/.active.profile`;
. /data/.siyah/${PROFILE}.profile;

if [ "$uksm_control" == "on" ]; then
	echo "1" > sys/kernel/mm/uksm/run
	echo "500" > /sys/kernel/mm/uksm/sleep_millisecs; # max: 1000
	echo "quiet" > /sys/kernel/mm/uksm/cpu_governor;
	echo "UKSM IS ACTIVE";
else
	echo "0" > sys/kernel/mm/uksm/run
	echo "UKSM IS DISABLED";
fi;
